#!/usr/bin/env python3
import os, re, subprocess, argparse
from glob     import glob
from tabulate import tabulate

DEFAULT_DIR = '.'

def validate_args():
    pass

def file_filter(file_name):
    regex_list = [
        '\.o$'
    ]
    return all([not re.search(r, file_name) for r in regex_list])


if __name__ == '__main__':
    parser = argparse.ArgumentParser(description='Quick Search')
    parser.add_argument('-f', '--filepattern', nargs=1, type=str, required=True)
    parser.add_argument('-e', '--echo', action='store_true')
    parser.add_argument('index', type=int, nargs=argparse.REMAINDER)
    pargs = parser.parse_args()

    validate_args()
    files = [y for x in os.walk(os.environ.get('SEARCH_ROOT', DEFAULT_DIR))
               for y in glob(os.path.join(x[0], '*')) if file_filter(y)]
    selected_files = sorted(list(filter(lambda x: re.search(pargs.filepattern[0], x, re.IGNORECASE),
                                        files)))

    file_table = [['Index', 'File']] + [[i+1, f] for i, f in enumerate(selected_files)]

    if pargs.index:
        file_name = file_table[pargs.index[0]][1]
        if pargs.echo:
            print(file_name)
        else:
            EDITOR = os.environ.get('EDITOR', 'vim')
            subprocess.call([EDITOR, file_name]) 
    else:
        print(tabulate(file_table, tablefmt='plain'))

